// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-BU4KiVjs8AiinudLYPBaYLiWMUadOY',
    appId: '1:151389024285:web:fb5203295b61cc5aa656f4',
    messagingSenderId: '151389024285',
    projectId: 'course-hotelio-68ee8',
    authDomain: 'course-hotelio-68ee8.firebaseapp.com',
    storageBucket: 'course-hotelio-68ee8.appspot.com',
    measurementId: 'G-5SZHFCYRFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwCV_hM9axPHjvWN_oAhRlcJQzmx9nQE',
    appId: '1:151389024285:android:e343993f5013065aa656f4',
    messagingSenderId: '151389024285',
    projectId: 'course-hotelio-68ee8',
    storageBucket: 'course-hotelio-68ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1rSKdsaUKYr7-iybaGcvcuhuT455RdI',
    appId: '1:151389024285:ios:fb98f90ac5c25159a656f4',
    messagingSenderId: '151389024285',
    projectId: 'course-hotelio-68ee8',
    storageBucket: 'course-hotelio-68ee8.appspot.com',
    iosBundleId: 'com.example.courseHotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1rSKdsaUKYr7-iybaGcvcuhuT455RdI',
    appId: '1:151389024285:ios:b6afe65e3003d3b0a656f4',
    messagingSenderId: '151389024285',
    projectId: 'course-hotelio-68ee8',
    storageBucket: 'course-hotelio-68ee8.appspot.com',
    iosBundleId: 'com.example.courseHotelio.RunnerTests',
  );
}
